let all_products = [
    { product_name : 'Adidas x 032c GSG Running TR', 
      available_size : [39, 40, 41, 42, 43], 
      price : 19150,
      brand : 'Adidas', 
      category: 'Кроссовки' },
    { product_name : 'ZX 1K Boost', 
      available_size : [40, 41, 43, 45, 46], 
      price : 9420,
      brand : 'Adidas Originals', 
      category : 'Кроссовки' },
    { product_name : 'Streetball 2.0',
      available_size : [38, 39, 40, 41, 43, 44, 46],
      brand : 'Adidas Orginals',
      price : 13800,
      category : 'Комбинированные кроссовки' },
    { product_name : 'Yeezy Boost 350 V2 Mono Mist',
      available_size : [38, 39, 40, 41, 40, 42, 43, 44, 45],
      price : 19000,
      brand : 'Adidas Originals',
      category : 'Кроссовки' },
    { product_name : 'Track.2', 
      available_size : [39, 40, 41, 42, 43, 45, 46],
      brand : 'Balenciaga', 
      category : 'Комбинированные кроссовки', 
      price : 77050 },
    { product_name : 'Speed',
      available_size : [40, 42, 43, 44, 45, 46 ],
      brand : 'Balenciaga',
      category : 'Текстильные кроссовки', 
      price : 59950 },
    { product_name : 'Balenciaga x Crocs',
      available_size : [41, 42, 44, 45, 46],
      brand : 'Balenciaga',
      category : 'Резиновые сапоги',
      price : 53300 },
    {
      product_name : 'Triple S Clear Sole',
      available_size : [42, 43, 45, 46],
      brand : 'Balenciaga',
      category : 'Кроссовки',
      price : 88100 },
    {
      product_name : 'Track Clear Sole',
      available_size : [39, 40, 42, 44, 45, 46],
      brand : 'Balenciaga',
      category : 'Кроссовки',
      price : 84900 },
    {
      product_name : 'Triple S',
      available_size : [42, 43, 44, 45, 46],
      brand : 'Balenciaga',
      category : 'Кроссовки',
      price : 78350 },
    { product_name : 'Zig Kinetica Edge', 
      available_size : [42, 43, 44, 45], 
      brand : 'Reebok', 
      price : 12040, 
      category : 'Кроссовки' },
    {
      product_name : 'Beatnik',
      available_size : [40, 41, 42, 43, 44, 45],
      brand : 'Reebok',
      price : 6800, 
      category : 'Текстильные сандалии' },
    { product_name : 'Zig Kinetica II', 
      brand : 'Reebok', 
      available_size : [38, 39, 40, 41, 42, 43, 44, 45], 
      price : 9710, 
      category : 'Кроссовки' },
    { product_name : 'Zig Kinetica II Edge GORE-TEX', 
      brand : 'Reebok',
      available_size : [39, 40, 41, 42, 43, 44, 45],
      price : 14570,
      category : 'Комбинированные кроссовки' }
  ];

export default all_products;